#define PLOOPY_DPI_OPTIONS { 800 }
#define PLOOPY_DPI_DEFAULT 0
#define OPT_SCALE 1
#define SCROLL_BUTT_DEBOUNCE 10
#define PLOOPY_DRAGSCROLL_MOMENTARY 1
#define PLOOPY_DRAGSCROLL_FIXED 1
#define PLOOPY_DRAGSCROLL_INVERT 1
#define PLOOPY_DRAGSCROLL_DPI 1
