OLED_ENABLE = yes
OLED_DRIVER = ssd1306
LTO_ENABLE = yes
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes

BOOTLOADER = atmel-dfu

TAP_DANCE_ENABLE = yes

COMMAND_ENABLE = yes
